/**
 * Code Generator Skill
 * Generates code based on requirements
 */

import { v4 as uuidv4 } from 'uuid';

/**
 * Execute code generation
 */
export default async function codeGeneratorSkill({ task, context }) {
  const result = {
    task,
    timestamp: new Date().toISOString(),
    files: [],
    summary: '',
  };

  try {
    // Analyze task and generate code
    const codeSpec = analyzeCodeRequest(task);
    
    if (!codeSpec.type) {
      result.summary = 'No code generation request detected';
      result.files = [];
      return result;
    }

    // Generate code based on type
    switch (codeSpec.type) {
      case 'html':
        result.files = generateHTML(codeSpec);
        break;
      case 'react':
        result.files = generateReact(codeSpec);
        break;
      case 'api':
        result.files = generateAPI(codeSpec);
        break;
      case 'script':
        result.files = generateScript(codeSpec);
        break;
      default:
        result.files = generateGeneric(codeSpec);
    }

    result.summary = `Generated ${result.files.length} file${result.files.length > 1 ? 's' : ''} for ${codeSpec.type} project`;

  } catch (error) {
    result.error = error.message;
    result.summary = `Code generation failed: ${error.message}`;
  }

  return result;
}

/**
 * Analyze code request
 */
function analyzeCodeRequest(task) {
  const spec = {
    type: null,
    name: 'app',
    description: task,
    features: [],
    framework: null,
  };

  // Detect project type
  if (/\b(html|css|web page|landing page|website)\b/i.test(task)) {
    spec.type = 'html';
    spec.framework = 'vanilla';
  } else if (/\b(react|jsx|next\.js)\b/i.test(task)) {
    spec.type = 'react';
    spec.framework = 'react';
  } else if (/\b(api|rest|endpoint|backend)\b/i.test(task)) {
    spec.type = 'api';
    spec.framework = 'node';
  } else if (/\b(script|automation|cli)\b/i.test(task)) {
    spec.type = 'script';
    spec.framework = 'bash';
  } else if (/\b(python|django|flask)\b/i.test(task)) {
    spec.type = 'api';
    spec.framework = 'python';
  } else {
    spec.type = 'html'; // Default
    spec.framework = 'vanilla';
  }

  // Extract project name
  const nameMatch = task.match(/^(?:create|build|make)\s+(?:a\s+)?(\w+)/i);
  if (nameMatch) {
    spec.name = nameMatch[1];
  }

  return spec;
}

/**
 * Generate HTML project
 */
function generateHTML(spec) {
  const files = [];
  const id = uuidv4().substring(0, 8);

  // HTML file
  files.push({
    path: `${spec.name}/index.html`,
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${spec.name}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header>
    <h1>${spec.name}</h1>
    <nav>
      <a href="#home">Home</a>
      <a href="#about">About</a>
      <a href="#contact">Contact</a>
    </nav>
  </header>
  
  <main>
    <section id="home">
      <h2>Welcome to ${spec.name}</h2>
      <p>This is a generated ${spec.type} project.</p>
      <button onclick="handleClick()">Click Me</button>
    </section>
    
    <section id="about">
      <h2>About</h2>
      <p>Generated by Agent Sandbox Code Generator</p>
    </section>
  </main>

  <footer>
    <p>&copy; 2024 ${spec.name}. Generated by AI.</p>
  </footer>

  <script src="script.js"></script>
</body>
</html>`,
  });

  // CSS file
  files.push({
    path: `${spec.name}/styles.css`,
    content: `/* ${spec.name} Styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.6;
  color: #333;
}

header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 1rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

header h1 {
  font-size: 1.5rem;
}

header nav a {
  color: white;
  text-decoration: none;
  margin-left: 1.5rem;
  opacity: 0.9;
}

header nav a:hover {
  opacity: 1;
}

main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

section {
  margin-bottom: 3rem;
  padding: 2rem;
  background: #f8f9fa;
  border-radius: 8px;
}

button {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
  margin-top: 1rem;
}

button:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
}

footer {
  background: #333;
  color: white;
  text-align: center;
  padding: 1.5rem;
}`,
  });

  // JS file
  files.push({
    path: `${spec.name}/script.js`,
    content: `// ${spec.name} - Main Script

document.addEventListener('DOMContentLoaded', () => {
  console.log('${spec.name} loaded successfully');
  
  // Add smooth scrolling
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth' });
      }
    });
  });
});

/**
 * Handle button click
 */
function handleClick() {
  alert('Button clicked! Generated by Agent Sandbox');
  console.log('User interaction recorded');
}

// Export for module usage
export { handleClick };`,
  });

  return files;
}

/**
 * Generate React component
 */
function generateReact(spec) {
  const files = [];
  const componentName = spec.name.charAt(0).toUpperCase() + spec.name.slice(1);

  files.push({
    path: `${spec.name}/${spec.name}.jsx`,
    content: `// ${componentName} React Component
// Generated by Agent Sandbox

import React, { useState, useEffect } from 'react';
import './${spec.name}.css';

export default function ${componentName}() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      // Add your data fetching logic here
      const response = await fetch('/api/data');
      if (!response.ok) throw new Error('Failed to fetch');
      const result = await response.json();
      setData(result);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error}</div>;

  return (
    <div className="${spec.name}">
      <h1>{componentName}</h1>
      <p>Generated React Component</p>
      {data && <pre>{JSON.stringify(data, null, 2)}</pre>}
    </div>
  );
}`,
  });

  files.push({
    path: `${spec.name}/${spec.name}.css`,
    content: `/* ${componentName} Styles */
.${spec.name} {
  padding: 2rem;
}

.${spec.name} h1 {
  color: #333;
}`,
  });

  return files;
}

/**
 * Generate API endpoint
 */
function generateAPI(spec) {
  return [{
    path: `${spec.name}/index.js`,
    content: `// ${spec.name} API
// Generated by Agent Sandbox

import express from 'express';
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// API routes
app.get('/api/${spec.name}', (req, res) => {
  res.json({
    message: '${spec.name} API',
    endpoints: ['GET /', 'GET /health'],
  });
});

app.listen(PORT, () => {
  console.log(\`${spec.name} API running on port \${PORT}\`);
});
`,
  }];
}

/**
 * Generate generic script
 */
function generateGeneric(spec) {
  return [{
    path: `${spec.name}.sh`,
    content: `#!/bin/bash
# ${spec.name}
# Generated by Agent Sandbox

echo "Starting ${spec.name}..."
echo "Task: ${spec.description}"

# Add your script logic here

echo "${spec.name} completed"
`,
  }];
}
