/**
 * Task Runner - Executes inside Docker container
 * This runs within the isolated container
 */

import { Redis } from 'ioredis';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load configuration
const configPath = process.env.CONFIG_PATH || '/app/config/default.json';
const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));

// Redis client
const redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');

/**
 * Send progress update
 */
async function sendProgress(progress) {
  const taskId = process.env.TASK_ID;
  if (!taskId) return;
  
  const data = {
    taskId,
    ...progress,
    timestamp: new Date().toISOString(),
  };
  
  try {
    await redis.publish(`${config.redis?.keyPrefix || 'agent:'}progress:${taskId}`, JSON.stringify(data));
  } catch (e) {
    // Ignore errors
  }
}

/**
 * Execute a task with available tools
 */
async function executeTask(taskData) {
  const { id: taskId, task, tools } = taskData;
  const results = {
    taskId,
    executedAt: new Date().toISOString(),
    steps: [],
    output: '',
  };

  await sendProgress({
    progress: 20,
    step: 'analyzing',
    message: 'Analyzing task requirements',
  });

  const steps = [];
  
  if (tools.includes('web_search')) {
    await sendProgress({
      progress: 40,
      step: 'searching',
      message: 'Searching for relevant information',
    });
    
    steps.push({
      tool: 'web_search',
      action: 'Search for relevant information',
      query: task.substring(0, 50),
      status: 'success',
    });
  }
  
  await sendProgress({
    progress: 60,
    step: 'processing',
    message: 'Processing information with AI',
  });
  
  if (tools.includes('llm')) {
    steps.push({
      tool: 'llm',
      action: 'Generate response using LLM',
      status: 'success',
      model: 'gpt-4o',
    });
  }
  
  if (tools.includes('github')) {
    await sendProgress({
      progress: 80,
      step: 'github',
      message: 'Performing GitHub operations',
    });
    
    steps.push({
      tool: 'github',
      action: 'GitHub operations',
      status: 'success',
      operations: ['read', 'write'],
    });
  }

  await sendProgress({
    progress: 90,
    step: 'formatting',
    message: 'Formatting output',
  });

  // Generate output based on task type
  let output = '';
  
  if (task.toLowerCase().includes('travel') || task.toLowerCase().includes('旅游')) {
    output = generateTravelPlan(task);
  } else if (task.toLowerCase().includes('github') || task.toLowerCase().includes('code')) {
    output = generateGitHubPlan(task);
  } else {
    output = generateGeneralResponse(task);
  }

  results.steps = steps;
  results.output = output;
  results.executedAt = new Date().toISOString();

  await sendProgress({
    progress: 100,
    step: 'completed',
    message: 'Task completed',
  });

  return results;
}

/**
 * Generate travel plan (example)
 */
function generateTravelPlan(task) {
  return `# 🌍 旅行规划

## 任务：${task}

### 📋 推荐行程

**Day 1-2: 目的地探索**
- 抵达并入住酒店
- 当地景点初探
- 当地美食体验

**Day 3-4: 深度游览**
- 主要景点游览
- 文化体验
- 当地特色活动

**Day 5-6: 休闲放松**
- 自然风光探索
- 购物休闲
- 美食探索

### 📦 必备物品清单
- [ ] 护照/身份证
- [ ] 换洗衣物
- [ ] 充电器
- [ ] 常用药品
- [ ] 旅行保险

### 💰 预算估算
- 交通：$500-1000
- 住宿：$800-1500
- 餐饮：$300-600
- 门票：$200-400

---
*Generated by Agent Sandbox*
`;
}

/**
 * Generate GitHub plan (example)
 */
function generateGitHubPlan(task) {
  return `# 📦 GitHub 任务规划

## 任务：${task}

### 🔧 执行步骤

1. **代码准备**
   - 克隆仓库
   - 创建分支
   - 实现功能

2. **测试验证**
   - 单元测试
   - 集成测试
   - 代码审查

3. **提交发布**
   - 提交代码
   - 创建 Pull Request
   - 合并到主分支

### 📝 代码示例

\`\`\`javascript
// 示例代码
function example() {
  console.log('Hello, World!');
}
\`\`\`

---
*Generated by Agent Sandbox*
`;
}

/**
 * Generate general response (example)
 */
function generateGeneralResponse(task) {
  return `# 📋 任务执行结果

## 原始任务
${task}

## 🤖 执行摘要

任务已成功处理！

### 使用的工具
- ✅ LLM (GPT-4o)
- ✅ 信息搜索
- ✅ 代码执行

### 📊 状态
- 状态：✅ 完成
- 时间：${new Date().toLocaleString()}

---
*Generated by Agent Sandbox*
`;
}

/**
 * Main entry point
 */
async function main() {
  const taskId = process.env.TASK_ID;
  
  if (!taskId) {
    console.error('❌ TASK_ID not set');
    process.exit(1);
  }

  console.log(`🚀 Starting task: ${taskId}`);

  try {
    // Read task file
    const taskFile = path.join(config.docker?.workspacePath || '/app/workspace', `${taskId}.json`);
    
    let taskData;
    
    if (fs.existsSync(taskFile)) {
      taskData = JSON.parse(fs.readFileSync(taskFile, 'utf-8'));
    } else {
      // Try to get from Redis
      taskData = JSON.parse(await redis.get(`${config.redis?.keyPrefix || 'agent:'}task:${taskId}`));
    }
    
    // Execute
    const results = await executeTask(taskData);
    
    // Write result
    const resultFile = path.join(config.docker?.workspacePath || '/app/workspace', `${taskId}_result.json`);
    fs.writeFileSync(resultFile, JSON.stringify(results, null, 2));
    
    console.log(`✅ Task completed: ${taskId}`);
    console.log(`📄 Result written to: ${resultFile}`);
    
    process.exit(0);
  } catch (error) {
    console.error(`❌ Task failed: ${error.message}`);
    
    // Write error result
    const resultFile = path.join(config.docker?.workspacePath || '/app/workspace', `${taskId}_result.json`);
    fs.writeFileSync(resultFile, JSON.stringify({
      taskId,
      status: 'failed',
      error: error.message,
    }, null, 2));
    
    process.exit(1);
  }
}

main();
